site_name: PEOPLE-ER k-Nearest Neighbors
site_url: https://www.people-er.github.io/k-NN/
repo_url: https://github.com/PEOPLE-ER/k-NN

nav:
- Home: index.md
- Documentation: 
    - Technical Documentation: about.md
    - Getting Started: getting_started.md

plugins:
  - mkdocs-jupyter:
      include_source: True
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

markdown_extensions:
  - mdx_truly_sane_lists
  - attr_list
  - pymdownx.arithmatex:
      generic: true
theme: 
  name: material
  icon:
    repo: fontawesome/brands/github
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css